# Generated by Django 4.2.13 on 2024-10-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_direccion_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.TextField(default=''),
        ),
    ]
